// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace oficina.Models;

public partial class OficinaDBContext : DbContext
{
    public OficinaDBContext()
    {
    }

    public OficinaDBContext(DbContextOptions<OficinaDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<OrdensServico> OrdensServicos { get; set; }

    public virtual DbSet<Servico> Servicos { get; set; }

    public virtual DbSet<Veiculo> Veiculos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {   
        if(!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("Data Source=NotedoChris;Initial Catalog=OficinaDB;Integrated Security=True; TrustServerCertificate=True");
        }
            
    }
        

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ClienteId).HasName("PK__Clientes__71ABD087804D3177");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Telefone)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OrdensServico>(entity =>
        {
            entity.HasKey(e => e.OrdemId).HasName("PK__OrdensSe__C35643FD09EB4665");

            entity.ToTable("OrdensServico");

            entity.Property(e => e.Observacoes)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Cliente).WithMany(p => p.OrdensServicos)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdensSer__Clien__3E52440B");

            entity.HasOne(d => d.Servico).WithMany(p => p.OrdensServicos)
                .HasForeignKey(d => d.ServicoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdensSer__Servi__403A8C7D");

            entity.HasOne(d => d.Veiculo).WithMany(p => p.OrdensServicos)
                .HasForeignKey(d => d.VeiculoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdensSer__Veicu__3F466844");
        });

        modelBuilder.Entity<Servico>(entity =>
        {
            entity.HasKey(e => e.ServicoId).HasName("PK__Servicos__C59767B6D4236650");

            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Preco).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Veiculo>(entity =>
        {
            entity.HasKey(e => e.VeiculoId).HasName("PK__Veiculos__A5253AB8811FEFAA");

            entity.Property(e => e.Marca)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Modelo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Placa)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Cliente).WithMany(p => p.Veiculos)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Veiculos__Client__398D8EEE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}