// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace oficina.Models;

public partial class Servico
{
    public int ServicoId { get; set; }

    public string Descricao { get; set; }

    public decimal Preco { get; set; }

    public virtual ICollection<OrdensServico> OrdensServicos { get; set; } = new List<OrdensServico>();
}