// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace oficina.Models;

public partial class Veiculo
{
    public int VeiculoId { get; set; }

    public int ClienteId { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public int? Ano { get; set; }

    public string Placa { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual ICollection<OrdensServico> OrdensServicos { get; set; } = new List<OrdensServico>();
}