// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace test.Model.Models;

public partial class Cliente
{
    public int ClienteId { get; set; }

    public string Nome { get; set; }

    public string Telefone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<OrdensServico> OrdensServicos { get; set; } = new List<OrdensServico>();

    public virtual ICollection<Veiculo> Veiculos { get; set; } = new List<Veiculo>();
}