// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace test.Model.Models;

public partial class OrdensServico
{
    public int OrdemId { get; set; }

    public int ClienteId { get; set; }

    public int VeiculoId { get; set; }

    public int ServicoId { get; set; }

    public DateOnly DataServico { get; set; }

    public string Observacoes { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Servico Servico { get; set; }

    public virtual Veiculo Veiculo { get; set; }
}